[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/checkout"
  to = "https://uniform9.mybigcommerce.com/cart.php?action=loadInCheckout&id=c27d4d4e-128f-420b-b5ce-4c0a008bfbc5&token=d367ba0b242444db70ffdaf6b30f3b51660305fe3f70910113ca35d093e50962"
  status = 302
  force = true

[[redirects]]
  from = "/login"
  to = "https://www.bigcommerce.com/"
  status = 200
  force = true

[[redirects]]
  from = "/test1"
  to = "/test2"
  status = 200
  force = true
