[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/checkout*"
  to = "https://uniform9.mybigcommerce.com/cart.php"
  query = {path = ":path"}
  status = 302
  force = true

[[redirects]]
  from = "/login"
  to = "https://www.bigcommerce.com/"
  status = 200
  force = true

[[redirects]]
  from = "/test1"
  to = "/test2"
  status = 200
  force = true
